const images = {
  FlowLoginImage: require("../assets/images/FlowLoginImage.webp"),
  LoginLogoImg: require("../assets/images/LoginLogoImg.webp"),
  loadernew: require("../assets/images/lodarnew.mp4"),
  loadernew2: require("../assets/images/lodarnew2.mp4"),
  Apikey: require("../assets/images/Apikey.webp"),
  Integrationguide: require("../assets/images/Integrationguide.webp"),
  startfree: require("../assets/images/startfree.webp"),
  viewanalytics: require("../assets/images/viewanalytics.webp"),
  graphicon: require("../assets/images/graphicon.webp"),
  bellicon: require("../assets/images/bellicon.webp"),
  FlowpipeLogo: require("../assets/images/FlowpipeLogo.png"),
  statement: require("../assets/images/statement.webp"),
  dashboardright: require("../assets/images/dashboardright.webp"),
  playstore: require("../assets/images/playstore.webp"),
  Appstore: require("../assets/images/Appstore.webp"),
  reportsempty: require("../assets/images/reportsempty.webp"),
  cardinsidelogo: require("../assets/images/cardinsidelogo.webp"),
  msgicon: require("../assets/images/msgicon.png"),
  Dashboard: require("../assets/images/Dashboard.png"),
  Myaccount: require("../assets/images/Myaccount.png"),
  Templates: require("../assets/images/Templates.png"),
  product: require("../assets/images/product.png"),
  reports: require("../assets/images/reports.png"),
  Billingplan: require("../assets/images/Billingplan.png"),
  bhim: require("../assets/images/bhim.webp"),
  API: require("../assets/images/API.png"),
  Apiusage: require("../assets/images/Apiusage.png"),


};
export default images;
